repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-yaml
    -   id: check-toml
    -   id: mixed-line-ending
        args: ["--fix=lf"]

-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
        name: Fmt for krabiecdsa
        files: ^ecdsa/
        args: ['--manifest-path=ecdsa/Cargo.toml', '--']
    -   id: cargo-check
        name: Cargo-check for krabiecdsa
        files: ^ecdsa/
        types: [file]
        args: ['--manifest-path=ecdsa/Cargo.toml']
    -   id: clippy
        name: Clippy for krabiecdsa
        files: ^ecdsa/
        types: [file]
        args: ['--manifest-path=ecdsa/Cargo.toml', '--', '-D', 'warnings']
